package com.trackai.backend.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.itextpdf.io.font.constants.StandardFonts;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.font.PdfFont;
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.action.PdfAction;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.SolidBorder;
import com.itextpdf.layout.element.Link;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Text;
import com.itextpdf.layout.properties.TextAlignment;
import com.trackai.backend.exception.ResumeProcessingException;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.util.ArrayList;
import java.util.List;

@Service
public class ResumePdfService {

    private static final DeviceRgb PRIMARY = new DeviceRgb(15, 52, 79);
    private static final DeviceRgb ACCENT = new DeviceRgb(8, 145, 178);
    private static final DeviceRgb BODY = new DeviceRgb(31, 41, 55);

    public byte[] create(JsonNode resume) {
        try {
            ByteArrayOutputStream output = new ByteArrayOutputStream();
            PdfFont regular = PdfFontFactory.createFont(StandardFonts.HELVETICA);
            PdfFont bold = PdfFontFactory.createFont(StandardFonts.HELVETICA_BOLD);

            try (PdfWriter writer = new PdfWriter(output);
                 PdfDocument pdf = new PdfDocument(writer);
                 Document document = new Document(pdf)) {

                document.setMargins(30, 46, 30, 46);
                pdf.getDocumentInfo()
                        .setTitle(text(resume, "name", "ATS Resume"))
                        .setAuthor(text(resume, "name", "CareerForge AI User"))
                        .setSubject("ATS-friendly resume generated by CareerForge AI");

                document.add(new Paragraph(text(resume, "name", "Candidate Name"))
                        .setFont(bold).setFontSize(22).setFontColor(PRIMARY).setTextAlignment(TextAlignment.CENTER)
                        .setMarginBottom(2));

                String headline = text(resume, "headline", "");
                if (!headline.isBlank()) {
                    document.add(new Paragraph(headline)
                            .setFont(bold).setFontSize(10.5f).setFontColor(ACCENT).setTextAlignment(TextAlignment.CENTER)
                            .setMarginTop(0).setMarginBottom(4));
                }

                JsonNode contactNode = resume.path("contact");
                if (!contactLine(contactNode).isBlank()) {
                    document.add(contactParagraph(contactNode, regular));
                    document.add(new Paragraph(" ")
                            .setBorderBottom(new SolidBorder(ACCENT, 1.1f)).setMarginTop(0).setMarginBottom(7));
                }

                addTextSection(document, bold, regular, "PROFESSIONAL SUMMARY", text(resume, "summary", ""));
                addSkills(document, bold, regular, resume.path("skills"));
                addExperience(document, bold, regular, resume.path("experience"));
                addProjects(document, bold, regular, resume.path("projects"));
                addEducation(document, bold, regular, resume.path("education"));
                addSimpleListSection(document, bold, regular, "CERTIFICATIONS", resume.path("certifications"));
            }
            return output.toByteArray();
        } catch (Exception ex) {
            throw new ResumeProcessingException(HttpStatus.INTERNAL_SERVER_ERROR,
                    "The ATS resume PDF could not be generated.", ex);
        }
    }

    private void addExperience(Document document, PdfFont bold, PdfFont regular, JsonNode items) {
        if (!items.isArray() || items.isEmpty()) return;
        addHeading(document, bold, "PROFESSIONAL EXPERIENCE");
        for (JsonNode item : items) {
            String titleCompany = joinNonBlank(" - ", text(item, "title", ""), text(item, "company", ""));
            document.add(new Paragraph(titleCompany).setFont(bold).setFontSize(10.5f).setMarginBottom(1));
            String meta = joinNonBlank(" | ",
                    joinNonBlank(" - ", text(item, "startDate", ""), text(item, "endDate", "")),
                    text(item, "location", ""));
            if (!meta.isBlank()) {
                document.add(new Paragraph(meta).setFont(regular).setFontSize(8.8f)
                        .setFontColor(ColorConstants.DARK_GRAY).setMarginTop(0).setMarginBottom(2));
            }
            addBullets(document, regular, item.path("bullets"));
        }
    }

    private void addProjects(Document document, PdfFont bold, PdfFont regular, JsonNode items) {
        if (!items.isArray() || items.isEmpty()) return;
        addHeading(document, bold, "PROJECTS");
        for (JsonNode item : items) {
            String line = joinNonBlank(" | ", text(item, "name", ""), text(item, "technologies", ""));
            document.add(new Paragraph(line).setFont(bold).setFontSize(10.2f).setMarginBottom(1));
            addBullets(document, regular, item.path("bullets"));
        }
    }

    private void addEducation(Document document, PdfFont bold, PdfFont regular, JsonNode items) {
        if (!items.isArray() || items.isEmpty()) return;
        addHeading(document, bold, "EDUCATION");
        for (JsonNode item : items) {
            String degree = joinNonBlank(" - ", text(item, "degree", ""), text(item, "institution", ""));
            document.add(new Paragraph(degree).setFont(bold).setFontSize(10.2f).setMarginBottom(1));
            String meta = joinNonBlank(" | ", text(item, "graduationDate", ""), text(item, "location", ""),
                    text(item, "details", ""));
            if (!meta.isBlank()) {
                document.add(new Paragraph(meta).setFont(regular).setFontSize(9)
                        .setFontColor(ColorConstants.DARK_GRAY).setMarginTop(0).setMarginBottom(4));
            }
        }
    }

    private void addSkills(Document document, PdfFont bold, PdfFont regular, JsonNode skills) {
        if (!skills.isArray() || skills.isEmpty()) return;
        List<String> values = new ArrayList<>();
        skills.forEach(node -> {
            if (!node.asText().isBlank()) values.add(node.asText().trim());
        });
        addTextSection(document, bold, regular, "CORE SKILLS", String.join(", ", values));
    }

    private void addSimpleListSection(Document document, PdfFont bold, PdfFont regular,
                                      String title, JsonNode values) {
        if (!values.isArray() || values.isEmpty()) return;
        addHeading(document, bold, title);
        values.forEach(value -> {
            if (!value.asText().isBlank()) {
                document.add(new Paragraph(value.asText().trim())
                        .setFont(regular).setFontSize(9.5f).setMarginTop(0).setMarginBottom(2));
            }
        });
    }

    private void addTextSection(Document document, PdfFont bold, PdfFont regular,
                                String title, String content) {
        if (content == null || content.isBlank()) return;
        addHeading(document, bold, title);
        document.add(new Paragraph(content.trim()).setFont(regular).setFontSize(9.7f)
                .setFontColor(BODY).setMultipliedLeading(1.18f).setMarginTop(0).setMarginBottom(5));
    }

    private void addHeading(Document document, PdfFont bold, String title) {
        document.add(new Paragraph(title).setFont(bold).setFontSize(10.2f)
                .setFontColor(PRIMARY).setCharacterSpacing(0.4f)
                .setBorderBottom(new SolidBorder(ACCENT, 0.7f)).setPaddingBottom(2)
                .setMarginTop(8).setMarginBottom(4));
    }

    private void addBullets(Document document, PdfFont regular, JsonNode bullets) {
        if (!bullets.isArray()) return;
        bullets.forEach(bullet -> {
            String value = bullet.asText().trim();
            if (!value.isBlank()) {
                document.add(new Paragraph("- " + value).setFont(regular).setFontSize(9.4f)
                        .setFontColor(BODY).setMarginLeft(9).setMarginTop(0).setMarginBottom(1.5f)
                        .setMultipliedLeading(1.16f));
            }
        });
    }

    private Paragraph contactParagraph(JsonNode contact, PdfFont regular) {
        Paragraph paragraph = new Paragraph()
                .setFont(regular).setFontSize(9).setTextAlignment(TextAlignment.CENTER)
                .setFontColor(ColorConstants.DARK_GRAY).setMarginTop(0).setMarginBottom(5);
        List<ContactPart> parts = List.of(
                new ContactPart(text(contact, "email", ""), "mailto:" + text(contact, "email", "")),
                new ContactPart(text(contact, "phone", ""), ""),
                new ContactPart(text(contact, "location", ""), ""),
                new ContactPart(text(contact, "linkedin", ""), text(contact, "linkedin", "")),
                new ContactPart(text(contact, "github", ""), text(contact, "github", "")),
                new ContactPart(text(contact, "portfolio", ""), text(contact, "portfolio", "")));
        boolean first = true;
        for (ContactPart part : parts) {
            if (part.label().isBlank()) continue;
            if (!first) paragraph.add(new Text(" | "));
            if (safeLink(part.uri())) {
                paragraph.add(new Link(part.label(), PdfAction.createURI(part.uri())).setFontColor(ACCENT));
            } else {
                paragraph.add(new Text(part.label()));
            }
            first = false;
        }
        return paragraph;
    }

    private boolean safeLink(String value) {
        return value.startsWith("https://") || value.startsWith("http://") || value.startsWith("mailto:");
    }

    private record ContactPart(String label, String uri) {}
    private String contactLine(JsonNode contact) {
        return joinNonBlank(" | ",
                text(contact, "email", ""),
                text(contact, "phone", ""),
                text(contact, "location", ""),
                text(contact, "linkedin", ""),
                text(contact, "github", ""),
                text(contact, "portfolio", ""));
    }

    private String text(JsonNode node, String field, String fallback) {
        if (node == null || node.path(field).isMissingNode() || node.path(field).isNull()) return fallback;
        String value = node.path(field).asText("").trim();
        return value.isBlank() ? fallback : value;
    }

    private String joinNonBlank(String delimiter, String... values) {
        List<String> present = new ArrayList<>();
        for (String value : values) {
            if (value != null && !value.isBlank()) present.add(value.trim());
        }
        return String.join(delimiter, present);
    }
}
